name: Azure DevOps Pipelines - Matrix Strategy

trigger: none

stages:
- stage: Build_Stage
  jobs:

  - job: Build
    strategy:
      matrix:
        Python35:
          PYTHON_VERSION: '3.5'
        Python36:
          PYTHON_VERSION: '3.6'
        Python37:
          PYTHON_VERSION: '3.7'
      maxParallel: 3
    steps:
    - checkout: none
    - script: echo $(PYTHON_VERSION)

- stage: Test_Stage
  jobs:
  - job: Test
    strategy:
      matrix:
        WindowsServer2022:
          imageName: 'windows-2022'
          script: 'set'
        WindowsServer2019:
          imageName: 'windows-2019'
          script: 'set'
        ubuntu-22-04:
          imageName: 'ubuntu-22.04'
          script: 'printenv'
        ubuntu-20-04:
          imageName: 'ubuntu-20.04'
          script: 'printenv'
        macos-12-monterey:
          imageName: 'macOS-12'
          script: 'printenv'
        macos-11-bigsur:
          imageName: 'macOS-11'
          script: 'printenv'
      maxParallel: 6
    pool:
      vmImage: $(imageName)
    steps:
    - checkout: none
    - script: |
        echo $(imageName)
        $(script)

- stage: Prod_Stage
  jobs:
  - job: Prod
    strategy:
      matrix:
        Deploy_Prod_EastEurope:
          location: 'East-europe'
        Deploy_Prod_WestEurope:
          location: 'west-europe'
        Deploy_Prod_EastUS:
          location: 'east-us'
        Deploy_Prod_WestUS:
          location: 'west-us'
      maxParallel: 1
    pool:
      vmImage: 'ubuntu-22.04'
    steps:
    - checkout: none
    - script: |
        echo 'Started deploying app to region $(location)...'